# Generated by Django 4.2.21 on 2025-07-17 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='alertahorario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='operador',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='pieza',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tecnico',
        ),
        migrations.DeleteModel(
            name='AlertaHorario',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
